# Generated by Django 2.2.6 on 2019-11-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment_details',
            fields=[
                ('aprt_name', models.CharField(max_length=30)),
                ('aprt_add', models.TextField()),
                ('aprt_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('survey_no', models.CharField(max_length=10)),
                ('bhk', models.IntegerField()),
                ('cost_per_bhk', models.IntegerField()),
                ('facing', models.CharField(max_length=10)),
                ('other_expences', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default=False, max_length=10)),
                ('aprt_img', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Employees_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(unique=True)),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_emailid', models.EmailField(max_length=254)),
                ('emp_mblno', models.IntegerField()),
                ('emp_salary', models.IntegerField()),
                ('emp_doj', models.DateField(auto_now_add=True)),
                ('emp_designation', models.CharField(max_length=10)),
                ('emp_work_location', models.TextField()),
                ('emp_remarks', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='plot_details',
            fields=[
                ('platno', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('roadno', models.CharField(max_length=20)),
                ('survey_no', models.CharField(max_length=10)),
                ('sq_yards', models.IntegerField(default=False)),
                ('cost_per_sq_yard', models.IntegerField()),
                ('other_expenses', models.IntegerField()),
                ('boundaries', models.CharField(max_length=30)),
                ('facing', models.CharField(max_length=10)),
                ('total_cost', models.IntegerField()),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default=False, max_length=10)),
                ('plot_image', models.FileField(default=False, upload_to='plot/')),
            ],
        ),
        migrations.CreateModel(
            name='user_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('user_name', models.CharField(max_length=30)),
                ('user_emailid', models.EmailField(max_length=254)),
                ('user_mblno', models.IntegerField()),
                ('user_created_date', models.DateField(auto_now_add=True)),
                ('user_addres', models.TextField()),
            ],
        ),
    ]
