# Generated by Django 2.2.6 on 2019-11-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartment_details',
            new_name='Appartment_details',
        ),
        migrations.RenameField(
            model_name='plot_details',
            old_name='other_expenses',
            new_name='other_expences',
        ),
    ]
